Update Dockerfile
kartoza/docker-geoserver pull request #354
Opened 2021-12-16 03:17 UTC by adonm

Update to 2.20.2 for http://geoserver.org/announcements/2021/12/13/logj4-rce-statement.html patches regarding  CVE-2021-44228 and CVE-2019-17571

2021-12-16 05:10 UTC, NyakudyaA requested changes
Please also change https://github.com/kartoza/docker-geoserver/blob/master/.env#L8 and https://github.com/kartoza/docker-geoserver/blob/master/.env#L4
Remove the logic https://github.com/kartoza/docker-geoserver/blob/master/scripts/setup.sh#L171
 This was used to update 2.20.1 and latest to patch that vulnerability

2021-12-16 05:43 UTC, lucernae commented
@NyakudyaA I think it is better to keep your patching logic in  https://github.com/kartoza/docker-geoserver/blob/master/scripts/setup.sh#L171 . We could patch older version of GeoServer image at runtime using that script.

2021-12-16 06:41 UTC, NyakudyaA commented
> @NyakudyaA I think it is better to keep your patching logic in https://github.com/kartoza/docker-geoserver/blob/master/scripts/setup.sh#L171 . We could patch older version of GeoServer image at runtime using that script.

@lucernae maybe we move the logic to start.sh so that it fixes older images on run time instead of setup stage

2021-12-17 02:22 UTC, adonm commented
Note I have tweaked as suggested (except for the patching logic), however until 2.20.2 is published to sourceforge the Dockerfile won't build - once they are published this request could be sensibly reviewed for a merge

2021-12-17 07:14 UTC, NyakudyaA approved these changes
Thanks, @adonm Let's wait till the new version is available before we merge this.

2021-12-28 14:27 UTC, jt-helsinki commented
Can you please check that all extensions are working before approving? MBStyles for example does not work. Version problem.

2021-12-28 21:10 UTC, NyakudyaA commented
> Can you please check that all extensions are working before approving? MBStyles for example does not work. Version problem.

@jt-helsinki can you open a new issue for this. We would rather have this addressed in a separate PR. Also describe what you mean by saying it doesn't work. Does it not install or the configuration is broken ?

2022-01-25 06:07 UTC, NyakudyaA commented
@adonm Can you please pull the latest changes from Master and fix the conflicts. Alternatively, can you also update https://github.com/kartoza/docker-geoserver/blob/master/scripts/setup.sh#L170 to have the following `if [[  -f ${GEOSERVER_INSTALL_DIR}/webapps/geoserver/WEB-INF/lib/log4j-1.2.17.jar ]] && [[ "${GS_VERSION}" -lt 2.20.2  ]] ; then`

2022-01-27 08:46 UTC, NyakudyaA commented
merged a PR to fix this and other missing commits from develop

2022-01-27 08:46 UTC, closed without merging