fix: update tomcat base image
kartoza/docker-geoserver pull request #671
Opened 2024-07-10 18:12 UTC by robertd

2024-07-10 19:13 UTC, NyakudyaA requested changes
@robertd You need to update the following files `. env`, github workflows

2024-07-10 20:53 UTC, robertd commented
@NyakudyaA It looks like it's having issues with clustering... https://github.com/kartoza/docker-geoserver/actions/runs/9881048084/job/27291190386?pr=671#step:7:1675

2024-07-12 18:45 UTC, NyakudyaA approved these changes

2024-07-14 08:50 UTC, NyakudyaA approved these changes
LGTM

2024-07-14 08:50 UTC, merged